const QUERY_PREFIX = 'queries/';

export const QUERY_TYPES = {
    QUERY_ERROR: QUERY_PREFIX + 'QUERY_ERROR',
    QUERY_INVALIDATE: QUERY_PREFIX + 'QUERY_INVALIDATE',
    QUERY_LOADED: QUERY_PREFIX + 'QUERY_LOADED',
    QUERY_LOADING: QUERY_PREFIX + 'QUERY_LOADING',
    QUERY_SUCCESS: QUERY_PREFIX + 'QUERY_SUCCESS',

};