const QUERY_PREFIX = 'queries/';

export const QUERY_TYPES = {
    QUERY_ERROR: QUERY_PREFIX + 'QUERY_ERROR',
    QUERY_INIT: QUERY_PREFIX + 'QUERY_INIT',
    QUERY_INVALIDATE: QUERY_PREFIX + 'QUERY_INVALIDATE',
    QUERY_LOADED: QUERY_PREFIX + 'QUERY_LOADED',
    QUERY_LOADING: QUERY_PREFIX + 'QUERY_LOADING',
    QUERY_SUCCESS: QUERY_PREFIX + 'QUERY_SUCCESS',

    QUERY_SEARCH_ERROR: QUERY_PREFIX + 'QUERY_SEARCH_ERROR',
    QUERY_SEARCH_FINISHED: QUERY_PREFIX + 'QUERY_SEARCH_FINISHED',
    QUERY_SEARCH_INIT: QUERY_PREFIX + 'QUERY_SEARCH_INIT',
    QUERY_SEARCH_SEARCHING: QUERY_PREFIX + 'QUERY_SEARCH_SEARCHING',
    QUERY_SEARCH_SUCCESS: QUERY_PREFIX + 'QUERY_SEARCH_SUCCESS',
};