

const PKG_PREFIX = 'packages/';

export const PKG_TYPES = {
    PACKAGE_LOADED: PKG_PREFIX + 'PACKAGE_LOADED',
    PACKAGE_LOADING: PKG_PREFIX + 'PACKAGE_LOADING',
    PACKAGES_LOADED: PKG_PREFIX + 'PACKAGES_LOADED',
    PACKAGES_LOADING: PKG_PREFIX + 'PACKAGES_LOADING',


    PACKAGE_SUCCESS: PKG_PREFIX + 'PACKAGE_SUCCESS',
    PACKAGES_SUCCESS: PKG_PREFIX + 'PACKAGES_SUCCESS',
    SET_ACTIVE_PACKAGE: PKG_PREFIX + 'SET_ACTIVE_PACKAGE',
    PACKAGES_SEARCH_FILTER: PKG_PREFIX + 'PACKAGES_SEARCH_FILTER',
};