const PKG_PREFIX = 'packages/';

export const PKG_TYPES = {
    PACKAGES_INIT: PKG_PREFIX + 'PACKAGE_INIT',

    PACKAGES_INVALIDATE: PKG_PREFIX + 'PACKAGES_INVALIDATE',
    PACKAGES_SUCCESS: PKG_PREFIX + 'PACKAGES_SUCCESS',
    PACKAGES_SEARCH_FILTER: PKG_PREFIX + 'PACKAGES_SEARCH_FILTER',
    PACKAGES_TOGGLE_DRAFTS: PKG_PREFIX + 'PACKAGES_TOGGLE_DRAFTS',
    SET_ACTIVE_PACKAGE: PKG_PREFIX + 'SET_ACTIVE_PACKAGE',
};

export const SND_PKG_SCHEMA: string = 'snd',
    SND_PKG_QUERY: string = 'pkgs',
    SND_CATEGORY_QUERY: string = 'pkgCategories';