
ALTER TABLE snd.Lookups ADD LookupId INT IDENTITY(1,1)
ALTER TABLE snd.Lookups DROP CONSTRAINT PK_SND_LOOKUPS
GO

ALTER TABLE snd.Lookups ADD CONSTRAINT PK_SND_LOOKUPS PRIMARY KEY (LookupId)

CREATE UNIQUE INDEX IDX_SND_LOOKUPS_LOOKUPSETID_VALUE ON snd.Lookups(LookupSetId, Value)