
CREATE INDEX IDX_SND_PKGS_LSID ON snd.Pkgs(Lsid);
CREATE INDEX IDX_SND_SUPERPKGS_LSID ON snd.SuperPkgs(Lsid);
CREATE INDEX IDX_SND_PKGCATEGORIES_LSID ON snd.PkgCategories(Lsid);
CREATE INDEX IDX_SND_PKGCATEGORYJUNCTION_LSID ON snd.PkgCategoryJunction(Lsid);
CREATE INDEX IDX_SND_PROJECTS_LSID ON snd.Projects(Lsid);
CREATE INDEX IDX_SND_PROJECTITEMS_LSID ON snd.ProjectItems(Lsid);
CREATE INDEX IDX_SND_EVENTS_LSID ON snd.Events(Lsid);
CREATE INDEX IDX_SND_CODEDEVENTS_LSID ON snd.CodedEvents(Lsid);
CREATE INDEX IDX_SND_EVENTNOTES_LSID ON snd.EventNotes(Lsid);

ALTER TABLE snd.Pkgs ADD Narrative NVARCHAR(MAX) NULL;
