const APP_PREFIX = 'app/';

export const APP_TYPES = {
    APP_CLEAR_MESSAGE: APP_PREFIX + 'APP_CLEAR_MESSAGE',
    APP_ERROR: APP_PREFIX + 'APP_ERROR',
    APP_ERROR_RESET: APP_PREFIX + 'APP_ERROR_RESET',
    APP_MESSAGE: APP_PREFIX + 'APP_MESSAGE',
    APP_WARNING: APP_PREFIX + 'APP_WARNING',
};
