const PKG_PREFIX = 'wizards/packages/';

export const PKG_WIZARD_TYPES = {
    PACKAGE_CHECK_VALID: PKG_PREFIX + 'PACKAGE_CHECK_VALID',
    PACKAGE_INIT: PKG_PREFIX + 'PACKAGE_INIT',
    PACKAGE_ERROR: PKG_PREFIX + 'PACKAGE_ERROR',
    PACKAGE_LOADED: PKG_PREFIX + 'PACKAGE_LOADED',
    PACKAGE_LOADING: PKG_PREFIX + 'PACKAGE_LOADING',
    PACKAGE_SUCCESS: PKG_PREFIX + 'PACKAGE_SUCCESS',
    PACKAGE_WARNING: PKG_PREFIX + 'PACKAGE_WARNING',
    PACKAGE_FULL_NARRATIVE: PKG_PREFIX + 'PACKAGE_FULL_NARRATIVE',
    PACKAGE_CLOSE_FULL_NARRATIVE: PKG_PREFIX + 'PACKAGE_CLOSE_FULL_NARRATIVE',

    SET_ACTIVE_PACKAGE: PKG_PREFIX + 'SET_ACTIVE_PACKAGE',

    SAVE_FIELD: PKG_PREFIX + 'SAVE_FIELD',
    SAVE_NARRATIVE: PKG_PREFIX + 'SAVE_NARRATIVE',

    RESET_SUBMISSION: PKG_PREFIX + 'SET_RESET_SUBMISSION',
    SET_SUBMITTED: PKG_PREFIX + 'SET_SUBMITTED',
    SET_SUBMITTING: PKG_PREFIX + 'SET_SUBMITTING',
};
